title: ''
baseURL: 'https://people.ucsc.edu/~lgilpin/'
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true
build:
  writeStats: true
enableGitInfo: false
summaryLength: 40
pagination:
  pagerSize: 20
enableEmoji: true
enableRobotsTXT: true
ignoreFiles: [".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
disableAliases: false
outputs:
  home: [HTML, RSS, headers, redirects, backlinks]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
  hint: picture
timeout: 600000
taxonomies:
  author: authors
  tag: tags
  category: categories
  publication_type: publication_types
markup:
  _merge: deep
  goldmark:
    renderer:
      unsafe: true
  highlight:
    lineNos: false
security:
  _merge: deep
sitemap:
  _merge: deep
